import { ContentOperations } from "../apps/desktop/src/main/content-operations";
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it,vi } from 'vitest';
import { openDatabase } from '@publisher/db';
import type { CredentialStore } from '@publisher/security';
import { AIProductCenter } from '../apps/desktop/src/main/ai-product-center';
const resources:{root:string;db:ReturnType<typeof openDatabase>['db']}[]=[];
it('keeps a paused in-flight title repair Unknown and requires an individual decision',async()=>{let calls=0,finish!:(value:Response)=>void;const f=fixture(async()=>{calls++;return calls===1?response('超'.repeat(50)):new Promise<Response>(resolve=>{finish=resolve;});});const operations=new ContentOperations(f.repository,f.center),queue=operations.createGenerationQueue({companyId:f.company.id,topic:'合成资料',requestedCount:1,targetPlatforms:['douyin'],profileId:f.profile.id,model:'fixture',templateId:'industry',templateVersion:1}),identity={companyId:f.company.id,queueId:queue.id};const running=operations.runGenerationQueue(identity);await vi.waitFor(()=>expect(calls).toBe(2));operations.pauseGenerationQueue(identity);finish(response('合成短标题'));await running;expect(f.repository.db.prepare('SELECT status FROM ai_request_journal ORDER BY created_at').all()).toEqual([{status:'Succeeded'},{status:'Unknown'}]);expect(f.center.history(f.company.id)[0]?.status).toBe('Unknown');expect(operations.snapshot(f.company.id).generationItems.some(item=>item.queueId===queue.id&&item.status==='Recoverable')).toBe(true);expect(()=>operations.retryFailedGeneration(identity)).toThrow();expect(calls).toBe(2);expect(f.repository.listArticles()).toHaveLength(0);});
afterEach(()=>{resources.splice(0).forEach(({root,db})=>{db.close();rmSync(root,{recursive:true,force:true});});});
function response(title='合成服务流程',body='合成企业甲有限公司提供服务流程资料。'){return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({title,body})}}],usage:{prompt_tokens:10,completion_tokens:20}}),{headers:{'content-type':'application/json'}});}
function fixture(fetchPort:typeof fetch){const root=mkdtempSync(join(tmpdir(),'r115-g-ai-fault-'));const {repository,db}=openDatabase(join(root,'publisher.db'),resolve('packages/db/migrations'));resources.push({root,db});const keys=new Map<string,string>();const credentials:CredentialStore={set:(k,v)=>{keys.set(k,v);},get:k=>keys.get(k)??null,delete:k=>{keys.delete(k);},has:k=>keys.has(k)};const center=new AIProductCenter(repository,credentials,fetchPort);const company=repository.createBrand({name:'合成企业甲',companyName:'合成企业甲有限公司'});const profile=center.saveProfile({provider:'custom',displayName:'本地模拟',baseUrl:'http://127.0.0.1:19001/v1',defaultModel:'fixture',isDefault:true});center.setCredential(profile.id,'synthetic-placeholder-key');const request={companyId:company.id,sourceArticleId:null,sourceText:'合成企业甲有限公司服务流程资料。',purpose:'生成文章',targetPlatforms:['douyin'],profileId:profile.id,model:'fixture',templateId:'industry',templateVersion:1};return{center,repository,company,profile,request};}
describe('G isolated AI result and request boundaries',()=>{
  it('counts same-model title repair separately and shows a bounded preview before dispatch',async()=>{let calls=0;const f=fixture(async()=>++calls===1?response('超'.repeat(50)):response('合成标题'));const preview=f.center.previewGeneration(f.request);expect(preview.baseRequests).toBe(1);expect(preview.maxRequests).toBe(2);expect(calls).toBe(0);const output=await f.center.generate({...f.request,previewId:preview.previewId});expect(output[0]?.title).toBe('合成标题');expect(calls).toBe(2);expect(f.center.requestBudget(preview.previewId,f.company.id).issuedRequests).toBe(2);expect(f.repository.listArticles()).toHaveLength(0);});
  it.each(['empty','truncated','malformed','oversize','rateLimit','timeout','streamLost'] as const)('preserves %s without auto retries or approval',async mode=>{let calls=0;const f=fixture(async()=>{calls++;if(mode==='timeout')throw new Error('fixture timeout');if(mode==='streamLost')return new Response(new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode('{'));controller.error(new Error('fixture disconnect'));}}));if(mode==='malformed')return new Response('not-json');if(mode==='oversize')return new Response('x'.repeat(2_000_001));if(mode==='rateLimit')return new Response('',{status:429});if(mode==='truncated')return new Response(JSON.stringify({choices:[{finish_reason:'length',message:{content:'partial'}}]}));return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:''}}]}));});const preview=f.center.previewGeneration(f.request);const result=await f.center.generate({...f.request,previewId:preview.previewId});expect(result[0]?.status).toBe(['timeout','streamLost'].includes(mode)?'Unknown':'Failed');expect(calls).toBe(1);expect(f.center.requestBudget(preview.previewId,f.company.id).issuedRequests).toBe(1);expect(f.repository.listArticles()).toHaveLength(0);});
  it('invalidates old previews on model/config/context/facts/source changes and prevents cross-company budget use',async()=>{let calls=0;const f=fixture(async()=>{calls++;return response();});const preview=f.center.previewGeneration(f.request);f.center.saveProfile({id:f.profile.id,provider:'custom',displayName:'本地模拟',baseUrl:'http://127.0.0.1:19001/v1',defaultModel:'changed-model',isDefault:true});await expect(f.center.generate({...f.request,previewId:preview.previewId})).rejects.toThrow('AI_PREVIEW_STALE');expect(calls).toBe(0);const other=f.repository.createBrand({name:'合成企业乙',companyName:'合成企业乙有限公司'});await expect(f.center.generate({...f.request,companyId:other.id,previewId:preview.previewId})).rejects.toThrow('AI_PREVIEW_STALE');});
  it('cancels an issued request, suppresses repair/additional targets and retains Unknown without new articles',async()=>{let finish:(response:Response)=>void=()=>{},calls=0;const f=fixture(async()=>{calls++;return new Promise<Response>(resolve=>{finish=resolve;});});const preview=f.center.previewGeneration({...f.request,targetPlatforms:['douyin','website']});const running=f.center.generate({...f.request,targetPlatforms:['douyin','website'],previewId:preview.previewId});await new Promise(resolve=>setTimeout(resolve,5));f.center.cancel(f.company.id);finish(response('超'.repeat(50)));const result=await running;expect(calls).toBe(1);expect(result[0]?.status).toBe('Unknown');expect(f.repository.listArticles()).toHaveLength(0);expect(f.center.requestBudget(preview.previewId,f.company.id).issuedRequests).toBe(1);});
});

it('previews N plus N times targets and counts bounded rate retries from the real AI port',async()=>{let calls=0;const f=fixture(async()=>{calls++;return calls<=2?new Response('',{status:429}):response(`合成流程 ${calls}`,`合成企业甲有限公司资料第${calls}项。`);});const operations=new ContentOperations(f.repository,f.center);const request={companyId:f.company.id,topic:'合成企业甲服务流程',requestedCount:1,targetPlatforms:['douyin'],profileId:f.profile.id,model:'fixture',templateId:'industry',templateVersion:1,concurrency:1};const preview=operations.previewGenerationQueue(request);expect(preview.workItemCount).toBe(2);expect(preview.maxRequests).toBe(8);const queue=operations.createGenerationQueue({...request,previewId:preview.previewId});await operations.runGenerationQueue({companyId:f.company.id,queueId:queue.id});expect(calls).toBe(4);expect(operations.generationQueue({companyId:f.company.id,queueId:queue.id}).issuedRequests).toBe(4);expect(operations.usage({companyId:f.company.id,days:7})[0]?.requestCount).toBe(4);expect(f.repository.listJobs()).toHaveLength(0);});
it('explicitly retries one Unknown into a new attempt while retaining its old history and budget',async()=>{let calls=0;const f=fixture(async()=>{calls++;if(calls===1)throw new Error('fixture disconnect');return response(`合成流程 ${calls}`,`合成企业甲有限公司资料第${calls}项。`);});const operations=new ContentOperations(f.repository,f.center);const request={companyId:f.company.id,topic:'合成资料',requestedCount:1,targetPlatforms:['douyin'],profileId:f.profile.id,model:'fixture',templateId:'industry',templateVersion:1};const queue=operations.createGenerationQueue(request);const identity={companyId:f.company.id,queueId:queue.id};await operations.runGenerationQueue(identity);expect(calls).toBe(1);const unknown=operations.snapshot(f.company.id).generationItems.find(item=>item.queueId===queue.id&&item.status==='Recoverable');if(!unknown)throw new Error('unknown item required');const old=unknown.generationId;operations.resolveRecoverableGeneration({...identity,itemId:unknown.id,decision:'retry'});await operations.runGenerationQueue(identity);expect(calls).toBe(3);expect(f.center.store.generation(old!)?.status).toBe('Unknown');expect(f.repository.db.prepare('SELECT COUNT(*) AS count FROM operations_generation_attempts WHERE item_id=?').get(unknown.id)).toEqual({count:2});expect(operations.generationQueue(identity).issuedRequests).toBe(3);});
it('aborts a real waiting fetch after queue cancellation and cannot save a late article',async()=>{let dispatched=false;const f=fixture(async(_url,init)=>{dispatched=true;return new Promise<Response>((_resolve,reject)=>{init?.signal?.addEventListener('abort',()=>reject(new Error('fixture aborted')),{once:true});});});const operations=new ContentOperations(f.repository,f.center);const queue=operations.createGenerationQueue({companyId:f.company.id,topic:'合成资料',requestedCount:1,targetPlatforms:['douyin'],profileId:f.profile.id,model:'fixture',templateId:'industry',templateVersion:1});const identity={companyId:f.company.id,queueId:queue.id};const running=operations.runGenerationQueue(identity);await new Promise(resolve=>setTimeout(resolve,5));expect(dispatched).toBe(true);operations.cancelGenerationQueue(identity);await running;expect(operations.generationQueue(identity).status).toBe('Cancelled');expect(f.repository.listArticles()).toHaveLength(0);expect(f.repository.db.prepare('SELECT status FROM ai_request_journal').all()).toEqual([{status:'Unknown'}]);});
it('preserves issued work as Unknown across an in-flight pause and refuses bulk retry',async()=>{let finish!:(value:Response)=>void;const f=fixture(async()=>new Promise<Response>(resolve=>{finish=resolve;}));const operations=new ContentOperations(f.repository,f.center);const queue=operations.createGenerationQueue({companyId:f.company.id,topic:'合成资料',requestedCount:1,targetPlatforms:['douyin'],profileId:f.profile.id,model:'fixture',templateId:'industry',templateVersion:1});const identity={companyId:f.company.id,queueId:queue.id};const running=operations.runGenerationQueue(identity);await new Promise(resolve=>setTimeout(resolve,5));operations.pauseGenerationQueue(identity);finish(response());await running;expect(f.repository.db.prepare('SELECT status FROM ai_request_journal').all()).toEqual([{status:'Unknown'}]);expect(f.center.history(f.company.id)[0]?.status).toBe('Unknown');expect(operations.snapshot(f.company.id).generationItems.some(item=>item.queueId===queue.id&&item.status==='Recoverable')).toBe(true);expect(()=>operations.retryFailedGeneration(identity)).toThrow();expect(f.repository.listArticles()).toHaveLength(0);});
it('blocks stale queue config and exhausted budgets before any mock request',async()=>{let calls=0;const f=fixture(async()=>{calls++;return response();});const operations=new ContentOperations(f.repository,f.center);const queue=operations.createGenerationQueue({companyId:f.company.id,topic:'合成资料',requestedCount:1,targetPlatforms:['douyin'],profileId:f.profile.id,model:'fixture',templateId:'industry',templateVersion:1});f.center.setCredential(f.profile.id,'changed-synthetic-key');await operations.runGenerationQueue({companyId:f.company.id,queueId:queue.id});expect(calls).toBe(0);expect(operations.generationQueue({companyId:f.company.id,queueId:queue.id}).issuedRequests).toBe(0);});
