import { afterEach, expect, it, vi } from "vitest";
import type { DraftWorkingCopy, DraftWorkingCopiesApi, DraftPersistInput } from "../apps/desktop/src/shared/draft-working-copies";
import { DraftAutosaveController } from "../apps/desktop/src/renderer/draft-autosave-controller";
const copy:DraftWorkingCopy={companyId:'c',documentKind:'Article',documentId:'a',copyId:'copy',baseVersion:'base',localVersion:0,baseSnapshot:{title:'标题',body:'正文'},snapshot:{title:'标题',body:'正文'},currentVersion:'base',currentSnapshot:{title:'标题',body:'正文'},hasChanges:false,activeEditing:true,status:'Editing',createdAt:'now',updatedAt:'now',persistedAt:'now'};
afterEach(()=>vi.useRealTimers());
function fixture(persist:(input:DraftPersistInput)=>Promise<DraftWorkingCopy>){const api={persist:vi.fn(persist),release:vi.fn(async()=>copy)} as unknown as DraftWorkingCopiesApi;return{api,controller:new DraftAutosaveController(copy,api,()=>{})};}
it('shows Saved only after Main acknowledges the current version',async()=>{vi.useFakeTimers();let release!:(value:DraftWorkingCopy)=>void;const pending=new Promise<DraftWorkingCopy>(done=>{release=done;});const{api,controller}=fixture(()=>pending);controller.capture({title:'修改',body:'正文'});await vi.advanceTimersByTimeAsync(400);expect(api.persist).toHaveBeenCalledTimes(1);expect(controller.state.phase).toBe('Saving');release({...copy,localVersion:1,snapshot:{title:'修改',body:'正文'},hasChanges:true});await controller.flush();expect(controller.state.phase).toBe('Saved');});
it('bounds continuous Chinese typing and keeps composition unmodified until compositionend',async()=>{vi.useFakeTimers();const{api,controller}=fixture(async input=>({...copy,localVersion:input.localVersion,snapshot:input.snapshot,hasChanges:true}));controller.composition(true);controller.capture({title:'zhong',body:'粘贴正文'});await vi.advanceTimersByTimeAsync(1000);expect(api.persist).not.toHaveBeenCalled();controller.composition(false);controller.capture({title:'中文',body:'粘贴正文'});for(let n=0;n<7;n++){await vi.advanceTimersByTimeAsync(100);controller.capture({title:'中文'+n,body:'粘贴正文'});}await vi.advanceTimersByTimeAsync(100);expect(api.persist).toHaveBeenCalled();expect(controller.snapshot.body).toBe('粘贴正文');await controller.flush();expect(controller.state.phase).toBe('Saved');});
it('keeps the last Main-confirmed snapshot when persistence fails and blocks leave',async()=>{vi.useFakeTimers();const{controller}=fixture(async()=>{throw new Error('synthetic disk failure');});controller.capture({title:'未落盘',body:'保留输入'});await expect(controller.leave()).rejects.toThrow('synthetic disk failure');expect(controller.confirmed.snapshot).toEqual(copy.snapshot);expect(controller.snapshot.title).toBe('未落盘');expect(controller.state.phase).toBe('Failed');});
it('a late acknowledgement never reports a newer unsaved revision as saved',async()=>{vi.useFakeTimers();let release!:(value:DraftWorkingCopy)=>void;const first=new Promise<DraftWorkingCopy>(done=>{release=done;});let calls=0;const{controller}=fixture(async input=>++calls===1?first:{...copy,localVersion:input.localVersion,snapshot:input.snapshot,hasChanges:true});controller.capture({title:'版本一',body:'正文'});await vi.advanceTimersByTimeAsync(400);controller.capture({title:'版本二',body:'正文'});release({...copy,localVersion:1,snapshot:{title:'版本一',body:'正文'}});await controller.flush();expect(controller.confirmed.snapshot.title).toBe('版本二');expect(controller.confirmed.localVersion).toBe(2);});
it.each(['commit','leave'] as const)('seals capture throughout an in-flight %s transition',async operation=>{let finish!:()=>void;const gate=new Promise<void>(resolve=>{finish=resolve;});const{controller,api}=fixture(async input=>({...copy,localVersion:input.localVersion,snapshot:input.snapshot,hasChanges:true}));api.commit=async()=>{await gate;return{...copy,articleId:'a',variantId:null,status:'Committed' as const};};api.release=async()=>{await gate;return{...copy,activeEditing:false};};controller.capture({title:'确认版本',body:'正文'});const pending=controller[operation]();await Promise.resolve();expect(()=>controller.capture({title:'迟到输入',body:'应禁止'})).toThrow('DRAFT_TRANSITION_IN_PROGRESS');finish();await pending;expect(controller.snapshot.title).toBe('确认版本');});
