import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { openDatabase } from '@publisher/db';
import { AiRequestGovernor } from '../apps/desktop/src/main/ai-request-budget';
const fixtures:ReturnType<typeof openDatabase>[]=[];const roots:string[]=[];
afterEach(()=>{fixtures.splice(0).forEach(item=>item.db.close());roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true}));});
function fixture(){const root=mkdtempSync(join(tmpdir(),'r115-g-ai-budget-'));roots.push(root);const opened=openDatabase(join(root,'publisher.db'),resolve('packages/db/migrations'));fixtures.push(opened);const company=opened.repository.createBrand({name:'合成预算企业',companyName:'合成预算企业有限公司'});const governor=new AiRequestGovernor(opened.repository);return{...opened,company,governor};}
const hash='a'.repeat(64), changed='b'.repeat(64);
function preview(governor:AiRequestGovernor,companyId:string,maxRequests=2){return governor.preview({kind:'Studio',companyId,sourceCount:1,targetCount:1,workItemCount:1,baseRequests:1,maxRequests,titleRepairAllowance:1,rateLimitRetryAllowance:0,globalConcurrency:1,maxOutputTokensPerRequest:3000,inputCharacters:100,model:'fixture',templateId:'industry',templateVersion:1,costEstimate:null,currency:null},hash,hash);}
it('requires a matching one-time preview and never refunds dispatched requests',async()=>{const {governor,company,repository}=fixture();const p=preview(governor,company.id);expect(()=>governor.activate(p.previewId,company.id,changed,hash)).toThrow('AI_PREVIEW_STALE');const p2=preview(governor,company.id);governor.activate(p2.previewId,company.id,hash,hash);expect(()=>governor.activate(p2.previewId,company.id,hash,hash)).toThrow();await expect(governor.run(p2.previewId,'fixture-1','Base',()=>hash,async()=>{throw Object.assign(new Error('transport lost'),{code:'TRANSPORT_UNKNOWN'});})).rejects.toThrow();await governor.run(p2.previewId,'fixture-2','TitleRepair',()=>hash,async()=>({tokenUsage:{input:2,output:3}}));await expect(governor.run(p2.previewId,'fixture-3','Base',()=>hash,async()=>({}))).rejects.toThrow('AI_BUDGET_EXHAUSTED');expect(governor.get(p2.previewId).issuedRequests).toBe(2);expect(repository.db.prepare('SELECT status FROM ai_request_journal ORDER BY rowid').all()).toEqual([{status:'Unknown'},{status:'Succeeded'}]);});
it('serializes requests from two companies through the same global lane',async()=>{const {governor,company,repository}=fixture();const other=repository.createBrand({name:'合成企业乙',companyName:'合成企业乙有限公司'});const p1=preview(governor,company.id),p2=preview(governor,other.id);governor.activate(p1.previewId,company.id,hash,hash);governor.activate(p2.previewId,other.id,hash,hash);let active=0,maximum=0;const action=async()=>{active++;maximum=Math.max(maximum,active);await new Promise(resolve=>setTimeout(resolve,5));active--;return {};};await Promise.all([governor.run(p1.previewId,'one','Base',()=>hash,action),governor.run(p2.previewId,'two','Base',()=>hash,action)]);expect(maximum).toBe(1);});
it('blocks cancellation and configuration drift before dispatch and counts late cancellation as unknown',async()=>{const {governor,company}=fixture();const p=preview(governor,company.id);governor.activate(p.previewId,company.id,hash,hash);const canceled=new AbortController();canceled.abort();await expect(governor.run(p.previewId,'one','Base',()=>hash,async()=>({}),canceled.signal)).rejects.toThrow('AI_CANCELED');await expect(governor.run(p.previewId,'two','Base',()=>changed,async()=>({}))).rejects.toThrow('AI_PREVIEW_STALE');expect(governor.get(p.previewId).issuedRequests).toBe(0);const late=new AbortController();await expect(governor.run(p.previewId,'three','Base',()=>hash,async()=>{late.abort();return {};},late.signal)).rejects.toThrow('TRANSPORT_UNKNOWN');expect(governor.get(p.previewId).issuedRequests).toBe(1);});
it('persists interrupted requests as unknown on restart without restoring budget',()=>{const {governor,company,repository}=fixture();const p=preview(governor,company.id);governor.activate(p.previewId,company.id,hash,hash);repository.db.prepare("UPDATE ai_request_budgets SET issued_requests=1 WHERE id=?").run(p.previewId);repository.db.prepare("INSERT INTO ai_request_journal(id,budget_id,generation_id,purpose,status,created_at) VALUES('crashed',?,'generation','Base','Started',?)").run(p.previewId,new Date().toISOString());const restarted=new AiRequestGovernor(repository);expect(restarted.get(p.previewId).issuedRequests).toBe(1);expect(repository.db.prepare("SELECT status FROM ai_request_journal WHERE id='crashed'").get()).toEqual({status:'Unknown'});});
