import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, expect, it } from "vitest";
import { openDatabase } from "@publisher/db";
import { createClosedSnapshot, validateFullSnapshot, restoreFullSnapshot } from "../apps/desktop/src/main/backup-restore";
const roots:string[]=[];
const identity={appVersion:'1.1.9',sourceCommit:'d00b5d60c75e2d121986f6b1c0679ce64c97e9f1',deliveryId:'R1.15-G',migrations:readdirSync(resolve('packages/db/migrations')).filter(name=>name.endsWith('.sql')).sort()};
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
function fixture(){const root=mkdtempSync(join(tmpdir(),'r115-g-backup-'));roots.push(root);const source=join(root,'source'),snapshot=join(root,'snapshot');mkdirSync(join(source,'production-data','media'),{recursive:true});const {db}=openDatabase(join(root,'fixture.db'),resolve('packages/db/migrations'));db.close();copyFileSync(join(root,'fixture.db'),join(source,'production-data','publisher.db'));writeFileSync(join(source,'Local State'),'encrypted-context-fixture');writeFileSync(join(source,'production-data','credentials.enc'),'encrypted-fixture');writeFileSync(join(source,'production-data','media','sample.png'),'synthetic-image-bytes');return{root,source,snapshot};}
it('verifies a closed full snapshot and restores into a new inert directory',()=>{const {root,source,snapshot}=fixture();const manifest=createClosedSnapshot(source,snapshot,identity,()=>true);expect(manifest.status).toBe('Complete');expect(validateFullSnapshot(snapshot,'1.1.9').valid).toBe(true);const destination=join(root,'restore');restoreFullSnapshot(snapshot,destination,'1.1.9',[source]);expect(readFileSync(join(destination,'production-data','publisher.db'))).toEqual(readFileSync(join(source,'production-data','publisher.db')));expect(JSON.parse(readFileSync(join(destination,'restore-pending-owner-review.json'),'utf8')).automaticExecutionDisabled).toBe(true);});
it('never labels an open source complete or overwrites a good snapshot',()=>{const{source,snapshot}=fixture();expect(()=>createClosedSnapshot(source,snapshot,identity,()=>false)).toThrow('SOURCE_NOT_CLOSED');createClosedSnapshot(source,snapshot,identity,()=>true);expect(()=>createClosedSnapshot(source,snapshot,identity,()=>true)).toThrow('DESTINATION_NOT_EMPTY');});
it('rejects tampering and missing Local State',()=>{const{source,snapshot}=fixture();createClosedSnapshot(source,snapshot,identity,()=>true);writeFileSync(join(snapshot,'production-data','media','sample.png'),'changed');expect(validateFullSnapshot(snapshot,'1.1.9').valid).toBe(false);const missing=join(snapshot,'Local State');rmSync(missing);expect(validateFullSnapshot(snapshot,'1.1.9').valid).toBe(false);});
it('rejects traversal, unsupported version, incomplete manifests and production restore',()=>{const{root,source,snapshot}=fixture();createClosedSnapshot(source,snapshot,identity,()=>true);expect(validateFullSnapshot(snapshot,'9.0.0').valid).toBe(false);expect(()=>restoreFullSnapshot(snapshot,join(source,'nested'),'1.1.9',[source])).toThrow('PROTECTED_DESTINATION');const path=join(snapshot,'manifest.json'),manifest=JSON.parse(readFileSync(path,'utf8'));manifest.files[0].path='../escape';writeFileSync(path,JSON.stringify(manifest));expect(validateFullSnapshot(snapshot,'1.1.9').valid).toBe(false);manifest.status='Incomplete';writeFileSync(path,JSON.stringify(manifest));expect(()=>restoreFullSnapshot(snapshot,join(root,'invalid'),'1.1.9',[source])).toThrow('SNAPSHOT_INVALID');});
it('checks migration provenance and remaps managed media in the restored copy only',()=>{
  const {root,source,snapshot}=fixture();const {db,repository}=openDatabase(join(root,'with-asset.db'),resolve('packages/db/migrations'));
  const company=repository.createBrand({name:'合成企业',companyName:'合成企业有限公司'});repository.createMediaAsset({brandId:company.id,type:'image',title:'隔离图片',filePath:join(source,'production-data','media','sample.png')});
  db.close();copyFileSync(join(root,'with-asset.db'),join(source,'production-data','publisher.db'));createClosedSnapshot(source,snapshot,identity,()=>true);
  const destination=join(root,'remapped');restoreFullSnapshot(snapshot,destination,'1.1.9',[source]);
  const restored=openDatabase(join(root,'readback.db'),resolve('packages/db/migrations'));restored.db.close();copyFileSync(join(destination,'production-data','publisher.db'),join(root,'readback.db'));
  const readback=openDatabase(join(root,'readback.db'),resolve('packages/db/migrations'));expect(readback.repository.listImageAssets()[0]?.filePath).toBe(join(destination,'production-data','media','sample.png'));readback.db.close();
  expect(validateFullSnapshot(snapshot,'1.1.9').valid).toBe(true);
  const manifest=JSON.parse(readFileSync(join(snapshot,'manifest.json'),'utf8'));manifest.migrations=['future.sql'];writeFileSync(join(snapshot,'manifest.json'),JSON.stringify(manifest));expect(validateFullSnapshot(snapshot,'1.1.9').valid).toBe(false);
});
it('cannot replay an old review marker or restore over its archive ancestor',()=>{const {root,source,snapshot}=fixture();writeFileSync(join(source,'restore-pending-owner-review.json'),JSON.stringify({automaticExecutionDisabled:false}));createClosedSnapshot(source,snapshot,identity,()=>true);const destination=join(root,'inert');restoreFullSnapshot(snapshot,destination,'1.1.9',[source]);expect(JSON.parse(readFileSync(join(destination,'restore-pending-owner-review.json'),'utf8')).automaticExecutionDisabled).toBe(true);expect(()=>restoreFullSnapshot(snapshot,root,'1.1.9',[])).toThrow('PROTECTED_DESTINATION');});
