import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { afterEach,expect,it,vi } from 'vitest';
import { openDatabase } from '@publisher/db';
import type { CredentialStore } from '@publisher/security';
import type { IpcDependencies } from '../apps/desktop/src/main/ipc';
import { CredentialWriteScope } from '../apps/desktop/src/main/credential-write-scope';
const handlers=vi.hoisted(()=>new Map<string,(_event:unknown,payload:unknown)=>Promise<unknown>>());
vi.mock('electron',()=>({ipcMain:{removeHandler:(channel:string)=>handlers.delete(channel),handle:(channel:string,handler:(_event:unknown,payload:unknown)=>Promise<unknown>)=>handlers.set(channel,handler)},app:{getPath:()=>'',getVersion:()=> '1.1.9'},dialog:{},shell:{}}));
import { registerIpc } from '../apps/desktop/src/main/ipc';
const resources:{root:string;db:ReturnType<typeof openDatabase>['db']}[]=[];
afterEach(()=>{for(const {root,db} of resources.splice(0)){db.close();rmSync(root,{recursive:true,force:true});}});
function fixture(check:()=>Promise<'logged_in'>){const root=mkdtempSync(join(tmpdir(),'r115-g-browser-auth-'));const {repository,db}=openDatabase(join(root,'publisher.db'),resolve('packages/db/migrations'));resources.push({root,db});repository.seedPlatformCatalog(resolve('PLATFORMS.csv'));const company=repository.createBrand({name:'合成公司',companyName:'合成公司有限公司'});repository.setSetting('operationsWorkspaceCompanyId',company.id);const account=repository.createAccount({platformKey:'toutiao',name:'合成账号'});db.prepare('INSERT INTO operations_account_company_bindings(account_id,company_id,bound_at,updated_at) VALUES(?,?,?,?)').run(account.id,company.id,'fixture','fixture');const values=new Map<string,string>(),store:CredentialStore={get:k=>values.get(k)??null,has:k=>values.has(k),set:(k,v)=>{values.set(k,v);},delete:k=>{values.delete(k);}};const scope=new CredentialWriteScope(store);const adapter={manifest:{platformKey:'toutiao',transport:'browser',authStrategy:'BrowserAutomation'},checkSession:check,completeConnection:check,connectAccount:async()=>({}),preparePublish:async()=>({}),getAccountProfile:async()=>({accountId:'synthetic-identity',accountName:'合成账号'}),persistConnectionSession:async()=>{scope.credentials.set('fixture-session','synthetic-session');},logout:async()=>{}};const registry={getForConnection:()=>adapter,getForContent:()=>adapter,tryGetForConnection:()=>adapter,tryGet:()=>adapter,getAccountConnectionMode:()=> 'BrowserAutomation'};registerIpc({repository,registry,publisher:{},scheduler:{},credentials:scope.credentials,aiCredentials:scope.credentials,runInAuthScope:<T>(guard:()=>boolean,operation:()=>Promise<T>)=>scope.run(guard,operation),resolveAccountSecrets:()=>({}),dataDirectory:root,coverDir:root,appLogPath:'',databasePath:join(root,'publisher.db'),logger:{info:()=>{},warn:()=>{},error:()=>{}}} as unknown as IpcDependencies);const invoke=(channel:string,payload:unknown)=>{const handler=handlers.get(channel);if(!handler)throw new Error('missing handler');return handler({},payload);};return{repository,account,invoke,values,adapter,scope};}
it.each(['accounts:refresh-login','accounts:complete-login'])('rejects %s success after Owner disables the account',async channel=>{let finish!:(value:'logged_in')=>void;const f=fixture(()=>new Promise(resolve=>{finish=resolve;}));const running=f.invoke(channel,{accountId:f.account.id,platformKey:'toutiao',...(channel==='accounts:complete-login'?{callbackUrl:''}:{})});await Promise.resolve();await f.invoke('accounts:update',{id:f.account.id,data:{enabled:false}});finish('logged_in');await expect(running).rejects.toThrow('ACCOUNT_AUTH_BINDING_CHANGED');expect(f.repository.getAccountById(f.account.id)?.enabled).toBe(false);expect(f.values.size).toBe(0);});
it('rejects completion after Owner changes state during session persistence',async()=>{const f=fixture(async()=> 'logged_in');let enter!:()=>void,finish!:()=>void;const entered=new Promise<void>(resolve=>{enter=resolve;});f.adapter.persistConnectionSession=async()=>{enter();await new Promise<void>(resolve=>{finish=resolve;});};const running=f.invoke('accounts:complete-login',{accountId:f.account.id,platformKey:'toutiao',callbackUrl:''});await entered;await f.invoke('accounts:update',{id:f.account.id,data:{enabled:false}});finish();await expect(running).rejects.toThrow('ACCOUNT_AUTH_BINDING_CHANGED');expect(f.repository.getAccountById(f.account.id)?.enabled).toBe(false);expect(f.repository.getAccountById(f.account.id)?.authorizationStatus).not.toBe('Authorized');});
it('does not delete a newer session or archive an account after a delayed disconnect',async()=>{const f=fixture(async()=> 'logged_in');let finish!:()=>void,enter!:()=>void;const entered=new Promise<void>(resolve=>{enter=resolve;});f.adapter.logout=async()=>{enter();await new Promise<void>(resolve=>{finish=resolve;});f.scope.credentials.delete('fixture-session');};f.values.set('fixture-session','old-synthetic-session');const running=f.invoke('accounts:disconnect',{accountId:f.account.id,platformKey:'toutiao'});await entered;await f.invoke('accounts:update',{id:f.account.id,data:{enabled:false}});f.values.set('fixture-session','new-synthetic-session');finish();await expect(running).rejects.toThrow('AUTH_REQUEST_SUPERSEDED');expect(f.values.get('fixture-session')).toBe('new-synthetic-session');expect(f.repository.getAccountById(f.account.id)?.archivedAt).toBeNull();});
