import { useEffect, useState, type JSX } from "react";
import { PageHeader as PageTitle, EmptyState } from "./design/WorkspacePrimitives";
import { flushDraftEditors } from "./draft-autosave-controller";

export function BackupsPage(): JSX.Element {
  const [backups,setBackups]=useState<string[]>([]),[full,setFull]=useState<Awaited<ReturnType<typeof window.publisherAPI.backups.fullList>>>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=():void=>{void Promise.all([window.publisherAPI.backups.list(),window.publisherAPI.backups.fullList()]).then(([db,snapshots])=>{setBackups(db);setFull(snapshots);}).catch(error=>setMessage(error instanceof Error?error.message:"无法读取备份列表"));};
  useEffect(load,[]);
  const act=async(operation:()=>Promise<string>):Promise<void>=>{setBusy(true);try{setMessage(await operation());load();}catch(error){setMessage(error instanceof Error?error.message:"备份操作失败，已有文件保留");}finally{setBusy(false);}};
  return <div className="backup-workspace"><PageTitle eyebrow="系统设置 / 备份与隔离恢复" title="备份与隔离恢复" description="数据库在线备份适合数据库回退；完整快照包含媒体、加密凭据上下文及浏览器资料，在正常关闭后创建并校验。"/>{message&&<div role="status" className="notice">{message}</div>}<section className="panel form-grid"><h3>创建备份</h3><div className="row-actions"><button className="secondary-button" disabled={busy} onClick={()=>void act(async()=>`数据库在线备份已创建：${await window.publisherAPI.backups.create()}（不包含媒体与凭据）`)}>仅备份数据库</button><button className="primary-button" disabled={busy} onClick={()=>void act(async()=>{await flushDraftEditors();const result=await window.publisherAPI.backups.queueFull();return `已安排正常退出后完整快照：${result.directory}`;})}>创建完整快照并正常退出</button></div><p>完整快照失败会标为 Incomplete 并保留现场；已有合格快照不会覆盖。</p></section><section className="panel form-grid"><h3>完整快照</h3>{full.length===0&&<EmptyState title="还没有完整快照" description="正常退出创建后，重新启动查看校验结果。完整快照与数据库在线备份分别校验。"/>}{full.map(item=><article key={item.directory}><strong>{item.status==="Complete"?"完整快照已完成":"快照未完成"}</strong><p className="path-text">{item.directory}</p><p>{item.createdAt} · {(item.totalBytes/1024/1024).toFixed(1)} MB</p><div className="row-actions"><button className="secondary-button" disabled={busy} onClick={()=>void act(async()=>{const result=await window.publisherAPI.backups.validateFull(item.directory);return `${result.valid?"校验通过":"校验失败"}：${result.message}`;})}>校验完整快照</button><button className="secondary-button" disabled={busy||item.status!=="Complete"} onClick={()=>void act(async()=>{const result=await window.publisherAPI.backups.restoreIsolated(item.directory);return `已恢复到新的隔离目录：${result.directory}。自动执行已暂停；请按恢复说明启动、核对身份和未知结果。`;})}>恢复到新隔离目录</button></div></article>)}</section><section className="panel form-grid"><h3>数据库在线备份历史</h3>{backups.map(path=><article key={path}><p className="path-text">{path}</p><button className="secondary-button" disabled={busy} onClick={()=>void act(async()=>{const result=await window.publisherAPI.backups.validate(path);return `${result.valid?"校验通过":"校验失败"}：${result.message}`;})}>校验数据库</button></article>)}</section></div>;
}

