import { useEffect, useState } from "react";
import type { JSX } from "react";
import type { Account, Brand, ContentStrategy, PublishMode, PublishPlan } from "@publisher/domain";

export function PlansPageV031({ refresh }: { refresh: () => void }): JSX.Element {
  const [brands, setBrands] = useState<Brand[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [plans, setPlans] = useState<PublishPlan[]>([]); const [brandId, setBrandId] = useState(""); const [selectedAccounts, setSelectedAccounts] = useState<string[]>([]); const [strategy, setStrategy] = useState<ContentStrategy>("same_article"); const [publishMode, setPublishMode] = useState<PublishMode>("ASSISTED"); const [name, setName] = useState("工作日内容排期"); const [createdPlan, setCreatedPlan] = useState<string | null>(null);
  useEffect(() => { void Promise.all([window.publisherAPI.brands.list(), window.publisherAPI.accounts.list(), window.publisherAPI.plans.list()]).then(([nextBrands, nextAccounts, nextPlans]) => { setBrands(nextBrands); setAccounts(nextAccounts); setPlans(nextPlans); if (nextBrands[0]) setBrandId(nextBrands[0].id); }); }, [refresh]);
  const create = async (): Promise<void> => { if (!brandId || selectedAccounts.length === 0) return; await Promise.all(selectedAccounts.map((accountId) => window.publisherAPI.accounts.update(accountId, { publishMode: publishMode === "MANUAL" ? "manual" : publishMode === "AUTO" ? "auto" : publishMode === "ASSISTED" ? "assisted" : "inherit" }))); const plan = await window.publisherAPI.plans.create({ name, brandId, enabled: true, strategy, articlesPerDay: 1, accountIds: selectedAccounts, publishTimes: ["09:30"], reusePolicy: "once", minIntervalSeconds: 60, maxRetries: 3, consecutiveFailureThreshold: 3, startDate: new Date().toISOString().slice(0, 10), endDate: null }); setCreatedPlan(plan.id); refresh(); };
  const generate = async (planId: string): Promise<void> => { await window.publisherAPI.plans.generateJobs(planId, new Date(Date.now() - 1000).toISOString()); refresh(); };
  return <><PageTitle eyebrow="发布中心" title="发布计划" description="计划会把文章、账号和发布模式写入持久化队列；浏览器平台首阶段只允许用户最终确认。" /><div className="form-layout"><section className="panel form-panel"><div className="panel-heading"><div><h3>新建计划</h3><span>所有选择都会进入 SQLite 计划记录</span></div></div><label>计划名称<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>品牌<select value={brandId} onChange={(event) => setBrandId(event.target.value)}>{brands.map((brand) => <option value={brand.id} key={brand.id}>{brand.name}</option>)}</select></label><label>内容分配策略<select value={strategy} onChange={(event) => setStrategy(event.target.value as ContentStrategy)}><option value="same_article">全平台同文章</option><option value="per_platform">每个平台不同文章</option><option value="platform_variant">同主题按平台改写（使用已有 Variant）</option><option value="account_variant">每账号不同文章</option></select></label><label>发布模式<select value={publishMode} onChange={(event) => setPublishMode(event.target.value as PublishMode)}><option value="AUTO">AUTO · 用户确认后自动发布</option><option value="ASSISTED">ASSISTED · 自动准备，用户最终确认</option><option value="MANUAL">MANUAL · 仅生成内容</option></select></label><div className="hint-box">模式会应用到本次选择的账号。真实发布仍必须经过现有 Job Queue 和账号授权；Browser Automation 不会绕过验证码或风控。</div><label>选择账号<div className="template-list">{accounts.map((account) => <label className="check-row" key={account.id}><input type="checkbox" checked={selectedAccounts.includes(account.id)} onChange={() => setSelectedAccounts((current) => current.includes(account.id) ? current.filter((id) => id !== account.id) : [...current, account.id])} /><span>{account.name}</span><em>{account.platformKey} · {account.publishMode}</em></label>)}</div></label><button className="primary-button wide" disabled={!selectedAccounts.length} onClick={() => void create()}>保存发布计划</button>{createdPlan && <div className="notice success">计划已保存，策略：{strategy} · 模式：{publishMode}</div>}</section><section className="panel table-panel"><div className="panel-heading"><div><h3>已保存计划</h3><span>生成任务前仍可检查策略和账号范围</span></div></div>{plans.length === 0 ? <div className="empty-state compact"><strong>还没有发布计划</strong><p>配置一个计划开始测试。</p></div> : <div className="plan-list">{plans.map((plan) => <div className="plan-row" key={plan.id}><div><strong>{plan.name}</strong><span>{plan.strategy} · {plan.accountIds.length} 个账号</span></div><button className="secondary-button" onClick={() => void generate(plan.id)}>生成今日任务</button></div>)}</div>}</section></div></>;
}

function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }): JSX.Element { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{description}</p></div></div>; }
