import { AIWorkloadNotice } from "./AIWorkloadNotice";
import type { AIWorkloadPreview } from "../shared/ai-request-budget";
import { useEffect, useRef, useState } from "react";
import type { JSX } from "react";
import { STUDIO_PURPOSES, STUDIO_TARGETS, type Article, type Brand, type EnterpriseAIContext, type PromptTemplate } from "@publisher/domain";
import type { ProviderDefinition, ProviderKey, ModelDescriptor } from "@publisher/ai";
import type { GenerationHistory } from "@publisher/db";
import type { ProductProviderProfile, StudioOutput } from "../main/ai-product-center";
import { productErrorMessage, productPlatform } from "../shared/product-platform-policy";
import "./product-ai-center.css";
import { useWorkingDraft, DraftRecoveryNotice } from "./use-working-draft";
import { flushDraftEditors } from "./draft-autosave-controller";

type Tab = "studio" | "providers" | "context" | "templates" | "history";
const labels: Record<Tab, string> = { studio: "AI Content Studio", providers: "AI Provider Center", context: "企业 AI 资料", templates: "提示词模板", history: "生成历史" };
const issueLabels: Record<string, string> = { TITLE_EMPTY: "标题为空", BODY_EMPTY: "正文为空", TITLE_TOO_LONG: "标题超出平台长度限制，请人工缩短", COMPANY_MISMATCH: "出现其它企业名称", BRAND_MISMATCH: "出现其它品牌名称", CONTACT_MISMATCH: "联系方式与企业资料不符", FORBIDDEN_CLAIM: "含企业禁止使用的表述", UNAPPROVED_CLAIM: "认证、排名、客户或数据声明缺少已批准依据", DUPLICATE_TITLE: "最近同企业文章有相同标题", DUPLICATE_BODY: "最近同企业文章有相同正文", CONTENT_TYPE_MISMATCH: "内容类型不符合平台要求", BODY_POLICY_MISMATCH: "正文长度不符合平台要求" };
const split = (value: string) => value.split(/\n/gu).map(item => item.trim()).filter(Boolean);

export function ProductAICenter({ initialTab = "studio", refresh }: { initialTab?: Tab; refresh: () => void }): JSX.Element {
  const [tab, setTab] = useState<Tab>(initialTab), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const [brands, setBrands] = useState<Brand[]>([]), [articles, setArticles] = useState<Article[]>([]), [profiles, setProfiles] = useState<ProductProviderProfile[]>([]), [definitions, setDefinitions] = useState<readonly ProviderDefinition[]>([]);
  const [companyId, setCompanyId] = useState(""), [sourceId, setSourceId] = useState(""), [sourceText, setSourceText] = useState(""), [purpose, setPurpose] = useState<string>("平台适配"), [targets, setTargets] = useState<string[]>(["douyin"]);
  const [templates, setTemplates] = useState<PromptTemplate[]>([]), [templateKey, setTemplateKey] = useState("industry@1"), [profileId, setProfileId] = useState(""), [model, setModel] = useState(""), [outputs, setOutputs] = useState<StudioOutput[]>([]), [history, setHistory] = useState<GenerationHistory[]>([]);
  const [context, setContext] = useState<EnterpriseAIContext | null>(null), [templateEdit, setTemplateEdit] = useState<PromptTemplate | null>(null);
  const [providerEdit, setProviderEdit] = useState({ id: "", provider: "mimo" as ProviderKey, displayName: "Xiaomi MiMo", baseUrl: "https://api.xiaomimimo.com/v1", defaultModel: "mimo-v2.6-pro", isDefault: true });
  const [key, setKey] = useState(""), [models, setModels] = useState<ModelDescriptor[]>([]), [studioModels, setStudioModels] = useState<ModelDescriptor[]>([]);
  const [workload,setWorkload]=useState<AIWorkloadPreview|null>(null),[usedRequests,setUsedRequests]=useState<number|undefined>();
  useEffect(()=>{setWorkload(null);setUsedRequests(undefined);},[companyId,sourceId,sourceText,purpose,targets,profileId,model,templateKey]);
  const studioRequest=()=>{const [templateId,version]=templateKey.split("@");return {companyId,sourceArticleId:sourceId||null,sourceText,purpose,targetPlatforms:targets,profileId,model,templateId:templateId??"industry",templateVersion:Number(version)};};
  const activeAction = useRef(false);
  const reload = async (): Promise<void> => {
    const [nextProfiles, nextTemplates, nextHistory] = await Promise.all([window.publisherAPI.aiCenter.profiles(), window.publisherAPI.aiCenter.templates(), window.publisherAPI.aiCenter.history()]);
    setProfiles(nextProfiles); setTemplates(nextTemplates); setHistory(nextHistory);
  };
  useEffect(() => { void Promise.all([window.publisherAPI.brands.list(), window.publisherAPI.articles.list(), window.publisherAPI.aiCenter.definitions()]).then(([nextBrands, nextArticles, nextDefinitions]) => { setBrands(nextBrands); setArticles(nextArticles); setDefinitions(nextDefinitions); setCompanyId(nextBrands[0]?.id ?? ""); }).catch(() => setMessage("无法读取本地企业资料")); void reload().catch(() => setMessage("无法读取 AI 配置")); }, []);
  useEffect(() => {
    let current = true;
    setSourceId(""); setSourceText(""); setOutputs([]); setContext(null);
    if (companyId) void Promise.all([window.publisherAPI.operations.getStudioDefaults(companyId), window.publisherAPI.operations.consumePlanGenerationSeed(companyId)]).then(([value, seed]) => {
      if (!current) return;
      setProfileId(value.profileId ?? ""); setModel(value.model ?? ""); setTemplateKey(value.templateId ? `${value.templateId}@${value.templateVersion ?? 1}` : "industry@1"); setPurpose(value.purpose); setTargets(value.targetPlatforms);
      if (seed) { setSourceId(seed.articleId); setTargets(seed.targetPlatforms); setMessage(`已载入内容计划：${seed.topic}，生成结果保存为关联草稿版本。`); }
    }).catch(() => { if (current) setMessage("企业生成默认值或内容计划草稿暂时无法载入"); });
    if (companyId) void window.publisherAPI.aiCenter.context(companyId).then(value => { if (current) setContext(value); }).catch(() => { if (current) setMessage("企业资料暂时无法读取"); });
    return () => { current = false; };
  }, [companyId]);
  useEffect(() => { if (!profileId && profiles.length) { const profile = profiles.find(item => item.isDefault) ?? profiles[0]!; setProfileId(profile.id); setModel(profile.defaultModel); } }, [profiles, profileId]);
  const act = async (operation: () => Promise<void>): Promise<void> => { if (activeAction.current) return; activeAction.current = true; setBusy(true); setMessage(""); try { await operation(); } catch (error) { setMessage(error instanceof Error ? productErrorMessage(error) : "操作未完成，请重试"); } finally { activeAction.current = false; setBusy(false); } };
  const selectProfile = (id: string): void => { setProfileId(id); setModel(profiles.find(item => item.id === id)?.defaultModel ?? ""); setStudioModels([]); };
  const editProfile = (profile: ProductProviderProfile): void => { setProviderEdit({ id: profile.id, provider: profile.provider, displayName: profile.displayName, baseUrl: profile.baseUrl, defaultModel: profile.defaultModel, isDefault: profile.isDefault }); setKey(""); setModels([]); };
  const selectDefinition = (provider: ProviderKey): void => { const definition = definitions.find(item => item.key === provider)!; setProviderEdit({ id: "", provider, displayName: definition.displayName, baseUrl: definition.baseUrl, defaultModel: definition.presets[0] ?? "", isDefault: profiles.length === 0 }); setKey(""); setModels([]); };
  const updateOutput = (id: string, changes: Partial<StudioOutput>): void => setOutputs(current => current.map(item => item.generationId === id ? { ...item, ...changes } : item));
  const latestTemplates = templates.filter(item => !templates.some(other => other.templateId === item.templateId && other.version > item.version));
  const selectedProfile = profiles.find(item => item.id === profileId);
  return <div className="product-ai-center">
    <div className="page-title"><div><h2>{labels[tab]}</h2><p>从企业已确认资料生成本地草稿，人工编辑和审核后再走正式发布流程。</p></div></div>
    <div className="row-actions">{(Object.keys(labels) as Tab[]).map(item => <button key={item} className={tab === item ? "primary-button" : "secondary-button"} disabled={busy} onClick={() => void act(async () => { await flushDraftEditors(); setTab(item); })}>{labels[item]}</button>)}</div>
    {message && <div role="status" className="notice">{message}</div>}
    {busy&&tab==="studio"&&<button className="secondary-button" onClick={()=>void window.publisherAPI.aiCenter.cancel(companyId).then(()=>setMessage("已请求取消；已发出请求的结果需核对，不会自动追加请求。"))}>取消本次生成</button>}
    <fieldset disabled={busy} style={{ border: 0, padding: 0, minWidth: 0 }}>
    {tab === "providers" && <section className="panel form-grid">
      <h3>服务商配置</h3><label>服务商<select aria-label="AI 服务商" disabled={Boolean(providerEdit.id) || busy} value={providerEdit.provider} onChange={event => selectDefinition(event.target.value as ProviderKey)}>{definitions.map(item => <option key={item.key} value={item.key}>{item.displayName}</option>)}</select></label>
      <label>配置名称<input value={providerEdit.displayName} onChange={event => setProviderEdit(current => ({ ...current, displayName: event.target.value }))} /></label>
      <label>API 地址<input aria-label="AI API 地址" value={providerEdit.baseUrl} onChange={event => setProviderEdit(current => ({ ...current, baseUrl: event.target.value }))} /></label>
      <label>默认模型（允许手工 ID）<input aria-label="AI 默认模型" list="provider-models" value={providerEdit.defaultModel} onChange={event => setProviderEdit(current => ({ ...current, defaultModel: event.target.value }))} /><datalist id="provider-models">{models.map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</datalist></label>
      <label className="check-row"><input type="checkbox" checked={providerEdit.isDefault} onChange={event => setProviderEdit(current => ({ ...current, isDefault: event.target.checked }))} />设为默认模型</label>
      {providerEdit.provider !== "ollama" && <label>API Key（留空保留已保存凭据）<input aria-label="AI API Key" type="password" autoComplete="off" value={key} onChange={event => setKey(event.target.value)} /></label>}
      <div className="row-actions"><button className="primary-button" disabled={busy || !providerEdit.defaultModel.trim()} onClick={() => void act(async () => { const saved = await window.publisherAPI.aiCenter.saveProfile({ ...providerEdit, id: providerEdit.id || undefined }); if (key.trim()) { try { await window.publisherAPI.aiCenter.setCredential(saved.id, key); } finally { setKey(""); } } setProviderEdit(current => ({ ...current, id: saved.id })); await reload(); setMessage("配置已保存；凭据由系统安全存储保管。"); })}>保存服务商</button>
        <button className="secondary-button" disabled={busy || !providerEdit.id} title={!providerEdit.id ? "请先保存配置" : ""} onClick={() => void act(async () => { setModels(await window.publisherAPI.aiCenter.listModels(providerEdit.id)); setMessage("模型列表已加载，也可手工填写模型 ID。"); })}>获取模型列表</button>
        <button className="secondary-button" disabled={busy || !providerEdit.id} title={providerEdit.provider === "mimo" ? "发出一次最小文本请求，可能产生少量费用" : "读取模型列表验证连接"} onClick={() => void act(async () => { const result = await window.publisherAPI.aiCenter.testConnection(providerEdit.id); setMessage(result.message); await reload(); })}>Test Connection</button>
        <button className="secondary-button" disabled={busy} onClick={() => selectDefinition(providerEdit.provider)}>新建配置</button></div>
      <p>缺少 Key 时显示未配置；Ollama 只读取本机已有模型，不自动下载。模型列表不代表所有模型均支持文本生成。</p>
      {profiles.map(item => <div className="table-row" key={item.id}><strong>{item.displayName}</strong><span>{item.defaultModel}</span><span>{!item.configured ? "未配置" : item.verificationStatus === "Failed" ? "连接失败，请检查配置" : item.verificationStatus === "Unavailable" ? "本机服务或模型不可用" : item.lastVerifiedAt ? "已验证" : "已配置，待验证"}</span><span>{item.lastVerifiedAt ? new Date(item.lastVerifiedAt).toLocaleString("zh-CN") : "尚未验证"}</span><button className="mini-button" disabled={busy} onClick={() => editProfile(item)}>编辑配置</button></div>)}
    </section>}
    {tab === "studio" && <button className="secondary-button" disabled={busy || !companyId || !profileId || !model || !targets.length} onClick={() => void act(async () => { const [templateId, version] = templateKey.split("@"); await window.publisherAPI.operations.saveStudioDefaults({ companyId, profileId, model, templateId: templateId ?? null, templateVersion: Number(version) || null, purpose: purpose as typeof STUDIO_PURPOSES[number], targetPlatforms: targets as typeof STUDIO_TARGETS[number][] }); setMessage("当前企业的提示词默认值已保存"); })}>保存企业生成默认值</button>}
    {tab === "studio" && <><section className="panel form-grid"><label>企业<select aria-label="AI 企业" value={companyId} disabled={busy} onChange={event => setCompanyId(event.target.value)}><option value="">选择企业</option>{brands.map(item => <option key={item.id} value={item.id}>{item.companyName || item.name}</option>)}</select></label>
      <label>源文章<select aria-label="AI 源文章" value={sourceId} disabled={busy} onChange={event => setSourceId(event.target.value)}><option value="">粘贴源稿或资料</option>{articles.filter(item => item.brandId === companyId).map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
      {!sourceId && <label>源稿或资料<textarea aria-label="AI 源稿" rows={8} value={sourceText} disabled={busy} onChange={event => setSourceText(event.target.value)} /></label>}
      <label>用途<select value={purpose} onChange={event => setPurpose(event.target.value)} disabled={busy}>{STUDIO_PURPOSES.map(item => <option key={item}>{item}</option>)}</select></label>
      <label>Provider<select aria-label="生成服务商" value={profileId} disabled={busy} onChange={event => selectProfile(event.target.value)}><option value="">先配置服务商</option>{profiles.map(item => <option key={item.id} value={item.id}>{item.displayName}{item.configured ? "" : "（未配置）"}</option>)}</select></label>
      <label>Model（可选择或手工填写）<input aria-label="生成模型" list="studio-models" value={model} disabled={busy} onChange={event => setModel(event.target.value)} /><datalist id="studio-models">{studioModels.map(item => <option key={item.id} value={item.id}>{item.displayName}</option>)}</datalist></label>
      <button className="secondary-button" disabled={busy || !selectedProfile?.configured} onClick={() => void act(async () => { setStudioModels(await window.publisherAPI.aiCenter.listModels(profileId)); setMessage("可从模型列表选择，也可手工填写兼容的文本模型 ID。"); })}>读取可选模型</button>
      <label>Prompt Template<select aria-label="生成模板" value={templateKey} disabled={busy} onChange={event => setTemplateKey(event.target.value)}>{latestTemplates.filter(item => item.enabled).map(item => <option key={`${item.templateId}@${item.version}`} value={`${item.templateId}@${item.version}`}>{item.name} · v{item.version}</option>)}</select></label>
      <div><strong>目标平台</strong>{STUDIO_TARGETS.map(platform => <label className="check-row" key={platform}><input type="checkbox" disabled={busy} checked={targets.includes(platform)} onChange={event => setTargets(current => event.target.checked ? [...current, platform] : current.filter(item => item !== platform))} />{productPlatform(platform)?.displayName ?? platform}<span>{productPlatform(platform)?.ordinaryPublishEnabled ? "" : "草稿可生成，当前平台尚未开放正式发布"}</span></label>)}</div>
      <button className="secondary-button" disabled={busy||!companyId||!profileId||!model.trim()||!targets.length||!sourceId&&!sourceText.trim()} onClick={()=>void act(async()=>{await flushDraftEditors();setWorkload(await window.publisherAPI.aiCenter.previewGeneration(studioRequest()));setUsedRequests(undefined);setMessage("工作量已由 Main 计算；确认预算后才能发起生成。");})}>预览 AI 工作量</button>
      {workload&&<AIWorkloadNotice preview={workload} issued={usedRequests}/>}<button className="primary-button" disabled={busy||!workload||!selectedProfile?.configured||usedRequests!==undefined} onClick={()=>void act(async()=>{if(!workload)throw new Error("请先预览工作量");await flushDraftEditors();const result=await window.publisherAPI.aiCenter.generate({...studioRequest(),previewId:workload.previewId});setOutputs(result);setUsedRequests((await window.publisherAPI.aiCenter.requestBudget(workload.previewId,companyId)).issuedRequests);await reload();setMessage("生成已结束，请核对结果并保存 Draft；请求预算已保留。");})}>{busy?"正在生成…":"确认预算并生成本地草稿"}</button></section>
      {outputs.length > 0 && <p>生成结果已保留在本机生成历史。人工修改后请点击“保存 Draft”，再切换页面。</p>}
      {outputs.map(item => <StudioDraftEditor key={item.generationId} companyId={companyId} item={item} busy={busy} onChange={changes=>updateOutput(item.generationId,changes)} onSaved={async()=>{await reload();refresh();}} onMessage={setMessage} />)}</>}
    {tab === "context" && <section className="panel form-grid"><label>企业<select value={companyId} onChange={event => setCompanyId(event.target.value)}>{brands.map(item => <option key={item.id} value={item.id}>{item.companyName || item.name}</option>)}</select></label>{context && <>
      <label>企业名称<input value={context.companyName} onChange={event => setContext({ ...context, companyName: event.target.value })} /></label>
      {([ ["brandNames", "品牌名称"], ["serviceAreas", "服务地区"], ["coreServices", "核心服务"], ["verifiedSellingPoints", "已核实卖点"], ["approvedClaims", "已批准事实声明"], ["forbiddenClaims", "禁止表述"], ["seoKeywords", "SEO 关键词"], ["geoKeywords", "GEO 关键词"] ] as const).map(([field, label]) => <label key={field}>{label}（每行一项）<textarea rows={3} value={context[field].join("\n")} onChange={event => setContext({ ...context, [field]: split(event.target.value) })} /></label>)}
      {Object.entries(context.contactInfo).filter(([field]) => !["phone", "email"].includes(field)).map(([field, value]) => <label key={field}>联系方式 · {field}<input value={value} onChange={event => setContext({ ...context, contactInfo: { ...context.contactInfo, [field]: event.target.value } })} /></label>)}
      <label>联系电话<input value={context.contactInfo.phone ?? ""} onChange={event => setContext({ ...context, contactInfo: { ...context.contactInfo, phone: event.target.value } })} /></label><label>邮箱<input value={context.contactInfo.email ?? ""} onChange={event => setContext({ ...context, contactInfo: { ...context.contactInfo, email: event.target.value } })} /></label>
      <label>语气<input value={context.tone} onChange={event => setContext({ ...context, tone: event.target.value })} /></label><label>官方网站<input value={context.officialWebsite} onChange={event => setContext({ ...context, officialWebsite: event.target.value })} /></label>
      <button className="primary-button" disabled={busy} onClick={() => void act(async () => { setContext(await window.publisherAPI.aiCenter.saveContext(context)); setMessage("当前企业 AI 资料已保存"); })}>保存企业 AI 资料</button></>}</section>}
    {tab === "templates" && <section className="panel form-grid"><label>模板<select value={templateEdit?.templateId ?? ""} onChange={event => setTemplateEdit(latestTemplates.find(item => item.templateId === event.target.value) ?? null)}><option value="">选择模板</option>{latestTemplates.map(item => <option key={item.templateId} value={item.templateId}>{item.name} · v{item.version}</option>)}</select></label>{templateEdit && <>
      <label>名称<input value={templateEdit.name} onChange={event => setTemplateEdit({ ...templateEdit, name: event.target.value })} /></label><label>系统提示词<textarea rows={6} value={templateEdit.systemPrompt} onChange={event => setTemplateEdit({ ...templateEdit, systemPrompt: event.target.value })} /></label><label>用户模板<textarea rows={6} value={templateEdit.userPromptTemplate} onChange={event => setTemplateEdit({ ...templateEdit, userPromptTemplate: event.target.value })} /></label><p>可用占位符：purpose、context、source、platform、policy（使用双花括号）。历史版本保留。</p><label><input type="checkbox" checked={templateEdit.enabled} onChange={event => setTemplateEdit({ ...templateEdit, enabled: event.target.checked })} />启用</label>
      <button className="primary-button" disabled={busy} onClick={() => void act(async () => { setTemplateEdit(await window.publisherAPI.aiCenter.saveTemplate({ ...templateEdit, version: templateEdit.version + 1 })); await reload(); setMessage("新模板版本已保存，历史生成记录仍指向原版本。"); })}>保存新版本</button></>}</section>}
    {tab === "history" && <section className="panel"><h3>最近 200 次生成记录</h3>{history.length === 0 && <p>尚无生成记录。</p>}{history.map(item => <div className="table-row" key={item.generationId}><span>{brands.find(brand => brand.id === item.companyId)?.companyName || "企业"}</span><span>{productPlatform(item.targetPlatform)?.displayName}</span><span>{item.provider} / {item.model}</span><span>{item.templateId} v{item.templateVersion}</span><span>{new Date(item.createdAt).toLocaleString("zh-CN")}</span><span>{({ Running: "生成中", Generated: "已生成", NeedsUserAction: "需要修改", Failed: "失败", Unknown: "结果无法确认", Saved: "已保存" })[item.status]}</span><button className="mini-button" disabled={busy || ["Failed", "Running"].includes(item.status)} onClick={() => void act(async () => { await flushDraftEditors(); const draft = await window.publisherAPI.aiCenter.draft(item.generationId); if (draft) { setOutputs([{ ...draft, platformKey: item.targetPlatform, status: item.status }]); setTab("studio"); } else setMessage("该记录没有可编辑草稿"); })}>查看草稿</button></div>)}</section>}
    </fieldset>
  </div>;
}

function StudioDraftEditor({companyId,item,busy,onChange,onSaved,onMessage}:{companyId:string;item:StudioOutput;busy:boolean;onChange:(changes:Partial<StudioOutput>)=>void;onSaved:()=>Promise<void>;onMessage:(message:string)=>void}):JSX.Element{
  const [working,setWorking]=useState({title:item.title,body:item.body}),[pending,setPending]=useState(false);
  const hasKnownDraft=Boolean(item.title||item.body);
  const enabled=item.status!=="Failed"&&item.status!=="Saved"&&(item.status!=="Unknown"||hasKnownDraft);
  const draft=useWorkingDraft({companyId,documentKind:"StudioGeneration",documentId:item.generationId},enabled,snapshot=>{setWorking(snapshot);onChange({...snapshot,status:"NeedsUserAction"});});
  const capture=(field:"title"|"body",value:string):void=>{const next={...working,[field]:value};draft.capture(next);setWorking(next);onChange({...next,status:"NeedsUserAction"});};
  const act=async(operation:()=>Promise<void>):Promise<void>=>{setPending(true);try{await operation();}catch(error){onMessage(error instanceof Error?error.message:"草稿操作失败，文本仍保留");}finally{setPending(false);}};
  return <section className="panel form-grid"><h3>{productPlatform(item.platformKey)?.displayName}草稿 · {item.status==="Saved"?"已保存":item.status==="Unknown"?"结果无法确认":item.status==="Failed"?"生成失败":"待编辑审核"}</h3>{item.errorMessage&&<p>{item.errorMessage}</p>}
    {(item.status!=="Failed"&&(item.status!=="Unknown"||hasKnownDraft))&&<><label>标题<input aria-label={`${item.platformKey} 草稿标题`} value={working.title} disabled={busy||pending||draft.locked||!enabled||!draft.ready} onCompositionStart={()=>draft.composition(true)} onCompositionEnd={()=>draft.composition(false)} onChange={event=>capture("title",event.target.value)}/></label><label>正文<textarea aria-label={`${item.platformKey} 草稿正文`} rows={12} value={working.body} disabled={busy||pending||draft.locked||!enabled||!draft.ready} onCompositionStart={()=>draft.composition(true)} onCompositionEnd={()=>draft.composition(false)} onChange={event=>capture("body",event.target.value)}/></label>
    {enabled&&<DraftRecoveryNotice draft={draft}/>}{item.validation.errors.map(code=><div className="notice warning" key={code}>{issueLabels[code]??"生成内容尚未通过校验"}</div>)}{item.validation.warnings.map(code=><p key={code}>{issueLabels[code]??"内容需要人工复核"}</p>)}
    <div className="row-actions"><button className="secondary-button" disabled={busy||pending||draft.locked||!enabled||!draft.ready} onClick={()=>void act(async()=>{await draft.leave();const validation=await window.publisherAPI.aiCenter.validateDraft(item.generationId,working.title,working.body);onChange({validation,status:validation.errors.length?"NeedsUserAction":"Generated"});onMessage(validation.errors.length?"请修正红项":"确定性校验通过；仍需人工核对事实");})}>Validate 内容</button><button className="primary-button" disabled={busy||pending||draft.locked||!enabled||!draft.ready} onClick={()=>void act(async()=>{await draft.commit();onChange({status:"Saved"});await onSaved();onMessage("已保存内容库 Draft，提交修改后还需人工审核。");})}>保存 Draft</button></div></>}
  </section>;
}
