import { useEffect, useState } from "react";
import type { JSX } from "react";
import type { PublishJob } from "@publisher/domain";

export function QueuePageV031({ refresh }: { refresh: () => void }): JSX.Element {
  const [jobs, setJobs] = useState<PublishJob[]>([]); const [busy, setBusy] = useState<string | null>(null); const load = (): void => { void window.publisherAPI.jobs.list().then(setJobs); }; useEffect(load, [refresh]);
  const [message, setMessage] = useState("");
  const act = async (id: string, action: () => Promise<unknown>): Promise<void> => { setBusy(id); setMessage("");
    try {
      const result = await action();
      if (result && typeof result === "object" && "message" in result && typeof result.message === "string") setMessage(result.message);
    } catch (error) { setMessage(error instanceof Error ? error.message : "操作未完成，请查看任务状态。"); }
    finally { setBusy(null); load(); refresh(); } };
  return <><PageTitle eyebrow="发布中心" title="发布队列" description="Dry Run、人工确认、自动发布和未知提交结果都保留在持久化 Job 状态中。" action={<button className="secondary-button" onClick={() => void window.publisherAPI.jobs.recover().then(load)}>恢复安全任务</button>} />{message && <p role="status">{message}</p>}<section className="panel table-panel"><div className="table-summary"><span>共 {jobs.length} 个任务</span></div>{jobs.length === 0 ? <div className="empty-state compact"><strong>队列为空</strong><p>创建发布计划并生成今日任务。</p></div> : <div className="data-table"><div className="table-head queue-head"><span>任务</span><span>平台 / 账号</span><span>计划时间</span><span>状态</span><span>操作</span></div>{jobs.map((job) => <div className="table-row queue-row" key={job.id}><div><strong>{job.id.slice(0, 12)}</strong><small>文章 {job.articleId.slice(0, 8)}</small></div><span>{job.platformKey}<br /><small>{job.accountId.slice(0, 8)}</small></span><span>{new Date(job.scheduledAt).toLocaleString("zh-CN")}</span><span><StatusPill status={job.status} /><small>{job.dryRun ? "Dry Run" : "正式发布"}</small></span><div className="row-actions">{["Pending", "Scheduled", "Retry"].includes(job.status) && <button className="mini-button" disabled={busy === job.id} onClick={() => void act(job.id, () => window.publisherAPI.jobs.run(job.id))}>Dry Run / 执行</button>}{["AwaitingConfirmation", "DryRunPassed"].includes(job.status) && <><button className="mini-button" disabled={busy === job.id} onClick={() => void act(job.id, () => window.publisherAPI.jobs.confirm(job.id, false).then(() => window.publisherAPI.jobs.run(job.id)))}>确认正式发布</button><button className="mini-button" disabled={busy === job.id} onClick={() => void act(job.id, () => window.publisherAPI.jobs.confirm(job.id, true))}>重新 Dry Run</button></>}{job.status === "NeedsReconciliation" && <><button className="mini-button" disabled={busy === job.id} onClick={() => void act(job.id, () => job.platformKey === "zhihu" ? window.publisherAPI.jobs.reconcileBrowser(job.id) : window.publisherAPI.jobs.reconcile(job.id))}>{job.platformKey === "zhihu" ? "知乎只读回查" : "查询平台状态"}</button>{job.platformKey !== "zhihu" && <button className="mini-button" disabled={busy === job.id} onClick={() => void act(job.id, () => window.publisherAPI.jobs.reconcileNotSubmitted(job.id))}>核验未提交（只读）</button>}</>}</div></div>)}</div>}</section></>;
}

function PageTitle({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }): JSX.Element { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2><p>{description}</p></div>{action}</div>; }
function StatusPill({ status }: { status: string }): JSX.Element { return <span className="status-pill muted">{status}</span>; }
