import { contextBridge, ipcRenderer } from "electron";
import type { PublisherApi } from "../shared/api";

const invoke = <T>(channel: string, payload?: unknown): Promise<T> => ipcRenderer.invoke(channel, payload) as Promise<T>;

const api: PublisherApi = {
  dashboard: { get: () => invoke("dashboard:get") },
  videoAssets: { list: (filters) => invoke("video-assets:list", filters), pickVideo: () => invoke("video-assets:pick-video"), pickCover: () => invoke("video-assets:pick-cover"), create: (input) => invoke("video-assets:create", input), update: (id, input) => invoke("video-assets:update", { id, input }), preflight: (input) => invoke("video-assets:preflight", input) },
  brands: { list: () => invoke("brands:list"), create: (input) => invoke("brands:create", input), update: (id, data) => invoke("brands:update", { id, data }), assets: (brandId) => invoke("brands:assets", { brandId }), addAsset: (input) => invoke("brands:asset-create", input) },
  brandKnowledge: { list: (brandId) => invoke("brand-knowledge:list", { brandId }), create: (input) => invoke("brand-knowledge:create", input), update: (id, data) => invoke("brand-knowledge:update", { id, data }), delete: (id) => invoke("brand-knowledge:delete", { id }) },
  keywords: { templates: (brandId) => invoke("keywords:templates", { brandId }), items: (brandId) => invoke("keywords:items", { brandId }), createTemplate: (input) => invoke("keywords:create-template", input), updateTemplate: (id, data) => invoke("keywords:update-template", { id, data }), deleteTemplate: (id) => invoke("keywords:delete-template", { id }), expand: (input) => invoke("keywords:expand", input), import: (brandId, source) => invoke("keywords:import", { brandId, source }), regions: (brandId) => invoke("keywords:regions", { brandId }), importRegions: (brandId, rows) => invoke("keywords:regions-import", { brandId, rows }) },
  articles: { list: (filters) => invoke("articles:list", filters), page: (filters) => invoke("articles:page", filters), get: (id) => invoke("articles:get", { id }), update: (id, data) => invoke("articles:update", { id, data }), markNeedsRewrite: (id) => invoke("articles:mark-needs-rewrite", { id }), archive: (id) => invoke("articles:archive", { id }), delete: (id) => invoke("articles:delete", { id }), generateCover: (id) => invoke("articles:generate-cover", { id }), attachRecommendedImage: (input) => invoke("articles:attach-recommended-image", input), variants: (articleId) => invoke("articles:variants", { articleId }), generateVariant: (articleId, platformKey) => invoke("articles:generate-variant", { articleId, platformKey }), updateVariant: (id, input) => invoke("articles:update-variant", { id, data: input }), history: (articleId) => invoke("articles:history", { articleId }), downloadTemplate: () => invoke("articles:excel-advanced-template"), downloadSimpleTemplate: () => invoke("articles:excel-simple-template"), downloadAdvancedTemplate: () => invoke("articles:excel-advanced-template"), importExcel: (defaultBrandId) => invoke("articles:excel-pick", { defaultBrandId }), confirmExcelImport: (preview, duplicateRowNumbers) => invoke("articles:excel-confirm", { preview, duplicateRowNumbers }), exportExcelErrors: (preview) => invoke("articles:excel-errors", { preview }), preparePublish: (input) => invoke("articles:prepare-publish", input) },
  imageAssets: { list: (filters) => invoke("image-assets:list", filters), pickFiles: () => invoke("image-assets:pick-files"), import: (input) => invoke("image-assets:import", input), update: (id, input) => invoke("image-assets:update", { id, input }), delete: (id) => invoke("image-assets:delete", { id }), selectForArticle: (input) => invoke("image-assets:select-for-article", input) },
  ai: { startBatch: (input) => invoke("ai:start-batch", input), task: (id) => invoke("ai:task", { id }), cancel: (id) => invoke("ai:cancel", { id }), profiles: () => invoke("ai:profiles"), upsertProfile: (input) => invoke("ai:profile-upsert", input), deleteProfile: (id) => invoke("ai:profile-delete", { id }) },
  contentStudio: { mediaAssets: (brandId) => invoke("content-studio:media-assets", { brandId }), expandKeywords: (input) => invoke("content-studio:expand-keywords", input), planTopics: (input) => invoke("content-studio:plan-topics", input), start: (input) => invoke("content-studio:start", input), task: (id) => invoke("content-studio:task", { id }), tasks: (brandId) => invoke("content-studio:tasks", { brandId }), versions: (rootTaskId, platformKey) => invoke("content-studio:versions", { rootTaskId, platformKey }), updateVersion: (id, input) => invoke("content-studio:version-update", { id, data: input }), regenerate: (rootTaskId, platformKey) => invoke("content-studio:regenerate", { rootTaskId, platformKey }) },
  quality: { items: (brandId) => invoke("quality:items", { brandId }), status: (contentType, contentId) => invoke("quality:status", { contentType, contentId }), history: (contentType, contentId) => invoke("quality:history", { contentType, contentId }), recheck: (contentType, contentId) => invoke("quality:recheck", { contentType, contentId }), decide: (contentType, contentId, status, reason) => invoke("quality:decide", { contentType, contentId, status, reason }) },
  humanReview: { dataset: () => invoke("human-review:dataset"), item: (id) => invoke("human-review:item", { id }), submit: (input) => invoke("human-review:submit", input) },
  qualityBenchmark: { run: (input) => invoke("quality-benchmark:run", input), control: (runId, status) => invoke("quality-benchmark:control", { runId, status }) },
  platforms: { list: () => invoke("platforms:list"), profiles: () => invoke("platforms:profiles"), contentRules: () => invoke("platforms:content-rules"), open: (platformKey) => invoke("platforms:open", { platformKey }) },
  accounts: { list: () => invoke("accounts:list"), overview: () => invoke("accounts:overview"), sessionHeartbeat: (accountId, platformKey, input) => invoke("accounts:session-heartbeat", { accountId, platformKey, ...(input ?? {}) }), inspectPublishEditor: (accountId, platformKey) => invoke("accounts:pre-submit-gate", { accountId, platformKey }), inspectEditorLoad: (accountId, platformKey) => invoke("accounts:editor-load-diagnostic", { accountId, platformKey }), inspectEditorNetworkFailure: (accountId, platformKey) => invoke("accounts:editor-network-diagnostic", { accountId, platformKey }), create: (input) => invoke("accounts:create", input), update: (id, data) => invoke("accounts:update", { id, data }), setCredentials: (input) => invoke("accounts:set-credentials", input), credentialStatus: (accountId, platformKey) => invoke("accounts:credential-status", { accountId, platformKey }), beginLogin: (accountId, platformKey) => invoke("accounts:begin-login", { accountId, platformKey }), completeLogin: (accountId, platformKey, callbackUrl) => invoke("accounts:complete-login", { accountId, platformKey, callbackUrl, pendingLogin: { accountId, platformKey } }), refreshLogin: (accountId, platformKey) => invoke("accounts:refresh-login", { accountId, platformKey }), cancelLogin: (accountId, platformKey) => invoke("accounts:cancel-login", { accountId, platformKey }), disconnect: (accountId, platformKey) => invoke("accounts:disconnect", { accountId, platformKey }), openBackend: (accountId, platformKey) => invoke("accounts:open-backend", { accountId, platformKey }), checkLogin: (accountId, platformKey) => invoke("accounts:check-login", { accountId, platformKey }) },
  platformSelfTest: { list: () => invoke("platform-self-test:list"), get: (testRunId) => invoke("platform-self-test:get", { testRunId }), runSafe: (platformAccountId) => invoke("platform-self-test:run-safe", { platformAccountId }), runPostUploadDiscovery: (input) => invoke("platform-self-test:run-post-upload-discovery", input), runPublishFlowExploration: (input) => invoke("platform-self-test:run-publish-flow-exploration", input), continue: (testRunId) => invoke("platform-self-test:continue", { testRunId }), runLevel: (platformAccountId, level) => invoke("platform-self-test:run-level", { platformAccountId, level }), healthCheck: () => invoke("platform-self-test:health-check"), requestPublish: (platformAccountId) => invoke("platform-self-test:request-publish", { platformAccountId }), confirmPublish: (testRunId, testVideoPath) => invoke("platform-self-test:confirm-publish", { testRunId, testVideoPath }), cancelPublish: (testRunId) => invoke("platform-self-test:cancel-publish", { testRunId }), requestOneShotPublish: (platformAccountId) => invoke("platform-self-test:request-one-shot-publish", { platformAccountId }), prepareOneShotPrepublish: (testRunId) => invoke("platform-self-test:prepare-one-shot-prepublish", { testRunId }), confirmOneShotPublish: (testRunId) => invoke("platform-self-test:confirm-one-shot-publish", { testRunId }), cancelOneShotPublish: (testRunId) => invoke("platform-self-test:cancel-one-shot-publish", { testRunId }), reconcileFailedOneShotConfirmation: (input) => invoke("platform-self-test:reconcile-failed-one-shot-confirmation", input), verifyXhsCreatorIdentity: (accountId) => invoke("platform-self-test:verify-xhs-creator-identity", { accountId }), probeXhsCanonicalPage: (accountId) => invoke("platform-self-test:probe-xhs-canonical-page", { accountId }), inspectCurrentXiaohongshuImageEditorReadiness: (accountId) => invoke("platform-self-test:inspect-current-xhs-image-editor-readiness", { accountId }), inspectCurrentXiaohongshuPublishEditorDom: (accountId) => invoke("platform-self-test:inspect-current-xhs-publish-editor-dom", { accountId }), inspectCurrentXiaohongshuPublishEditorSemanticCandidates: (accountId) => invoke("platform-self-test:inspect-current-xhs-publish-editor-semantic-candidates", { accountId }), inspectCurrentXiaohongshuPostUploadReconciliation: (accountId) => invoke("platform-self-test:inspect-current-xhs-post-upload-reconciliation", { accountId }), inspectCurrentXiaohongshuFileInputState: (accountId) => invoke("platform-self-test:inspect-current-xhs-file-input-state", { accountId }), verifyAndConvergeXhsIdentity: (accountId, ownerApproved = false) => invoke("platform-self-test:verify-and-converge-xhs-identity", { accountId, ownerApproved }), confirmDelete: (testRunId) => invoke("platform-self-test:confirm-delete", { testRunId }) },
  plans: { list: () => invoke("plans:list"), create: (input) => invoke("plans:create", input), generateJobs: (id, scheduledAt) => invoke("plans:generate-jobs", { id, scheduledAt }) },
  jobs: { list: (filters) => invoke("jobs:list", filters), createVideo: (input) => invoke("jobs:create-video", input), run: (id) => invoke("jobs:run", { id }), confirm: (id, dryRun = false) => invoke("jobs:confirm", { id, dryRun }), reconcile: (id) => invoke("jobs:reconcile", { id }), reconcileBrowser: (id) => invoke("jobs:reconcile-browser", { id }), reconcileNotSubmitted: (id) => invoke("jobs:reconcile-not-submitted", { id }), retry: (id) => invoke("jobs:retry", { id }), recover: () => invoke("jobs:recover") },
  logs: { list: (limit, filters) => invoke("logs:list", { limit, ...filters }), export: () => invoke("logs:export") },
  notifications: { list: (limit) => invoke("notifications:list", { limit }), markRead: (id) => invoke("notifications:read", { id }), markAllRead: () => invoke("notifications:read-all") },
  backups: { list: () => invoke("backups:list"), create: () => invoke("backups:create"), validate: (path) => invoke("backups:validate", { path }), restore: (path) => invoke("backups:restore", { path, confirm: true }) },
  settings: { get: () => invoke("settings:get"), update: (key, value) => invoke("settings:update", { key, value }), setSecret: (kind, value) => invoke("settings:set-secret", { kind, value }), testAi: () => invoke("settings:test-ai") }
};

contextBridge.exposeInMainWorld("publisherAPI", api);
